### ISSUE TITLE
Can't sync with google workspaces

### ISSUE THREAD

**Issue by iwex** [bitwarden/directory-connector#128]
Hello! When I set up Google sync and then click Test button I got "An error has occurred. Unexpected token in JSON at position 28". All changes were made through GUI, so I don't know what can be wrong.

**Comment by eliykat** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. To get support with your issue, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll be able to troubleshoot the problem with you, and if it is a bug, they'll reopen this thread for further action.

You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.

**Comment by iwex** [comment]
Hello! I've tried to debug all the things and come to the idea that bitwarden tried to fetch LDAP settings and then, if it's empty - it raises error mentioned in this issue. After setting dummy ldap settings and then filling gsuite settings - all is working correctly

**Comment by eliykat** [comment]
Hi @iwex, glad to hear you got it sorted. That does sound like a bug though. Can you please post a screenshot of the errors you get in the Developer Tools console when you don't have the dummy LDAP settings filled in?

**Comment by iwex** [comment]
@eliykat So, I added some debug lines to file where it's all failing (jslib/src/electron/services/electronRendererSecureStorage.service.ts): 
![image](https://user-images.githubusercontent.com/4510068/120941191-01578980-c72a-11eb-99b8-b685c0a17e1e.png)
At first I filled all fields in GSuite, switched to Dashboard tab -> click Test, everything is ok.
Then I switched to settings and got different providers loading: 
![image](https://user-images.githubusercontent.com/4510068/120941322-9f4b5400-c72a-11eb-8870-0dc68c8084e1.png)
After this manipulations I switched back to Dashboard and then to Settings: 
![image](https://user-images.githubusercontent.com/4510068/120941347-d9b4f100-c72a-11eb-8624-c280237dfed0.png)
