### ISSUE TITLE
Connector as a service (Windows)

### ISSUE THREAD

**Issue by SjamonDaal** [bitwarden/directory-connector#18]
Please add a service to the windows app to run the connector automatically without the requirement that the app needs to be opened.

**Comment by kspearrin** [comment]
You will need to do this manually using the bwdc CLI tool. You could create a scheduled task of a PowerShell script that does something like `bwdc sync`. See here for more info on using the CLI:

https://help.bitwarden.com/article/directory-sync/#command-line-interface

**Comment by caddac** [comment]
I'm trying to do this same thing. How do I tell the CLI to look for the `data.json` file in a directory that isn't my own user directory? IOW, I have a user designed to run the scheduled task without being logged in. However that user doesn't have access into my user directory. How can I set the `data-file` path?

**Comment by joeldeteves** [comment]
I have the same question as @caddac; I am unsure how to point bwdc.exe to a different data file path outside the default one.

**Comment by Yggdrasil** [comment]
This is still a relevant issue for my company. It's 3 years old now. Please consider starting to work on it.

**Comment by dwbit** [comment]
Hi everyone! Since this is a change/feature request, the issue will be closed and discussion can continue on the [Bitwarden Community Forums](https://community.bitwarden.com/). We're also exploring the possibility of including directory connector within the Bitwarden experience instead of as a separate application.
