### ISSUE TITLE
LDAPS support

### ISSUE THREAD

**Issue by frdmn** [bitwarden/directory-connector#2]
We noticed the connector doesn't support LDAPS as of yet. We plan to disable unencrypted connections to our Active Directory in the next months. For that we would need BitWarden to support those first. 

Is this on the roadmap?
 
Current directory-connector version: 1.2.0

**Comment by frdmn** [comment]
I just realized that the passwords are not checked against AD for imported users, is that correct? Each user has to set their own master password upon invitation, which is used to encrypt the data in the *personal* vault?

**Comment by scifire91** [comment]
@kspearrin can you confirm that users need to create their own password for bitwarden and can not use AD(synced) password?

**Comment by kspearrin** [comment]
@scifire91 The directory sync tool cannot share the LDAP credentials. Bitwarden works much differently than traditional web applications that only use the username/passwords for authentication. Bitwarden uses the user's password for authentication as well as the encryption key for all of their protected vault data. Because of this, a user must always enter the a bitwarden **master password** to unlock their vault's data. Unfortunately this type of secure design does not permit you to sync or share passwords with other systems, like LDAP credentials. Our directory sync tool is primarily used as a means for onboarding/offboarding of users within your organization's directory and controlling user access within the organization with groups.

**Comment by scifire91** [comment]
Thanks for that very detailed answer :) thought that this will not work by design but wanted it to confirmed

**Comment by frdmn** [comment]
Indeed, much appreciated!

**Comment by kspearrin** [comment]
LDAPS is now supported in the newest version (complete re-write of the application to a GUI).
