### ISSUE TITLE
Connection issues for sync groups with Microsoft Azure AD

### ISSUE THREAD

**Issue by amansilla** [bitwarden/directory-connector#244]
So we're evaluating Bitwarden for usage in the company. While trying to use the latest version  2.9.10 of the Directory connector, I'm not able to import any group; it seems not functional.

After login and configuring all Azure credentials, when clicking on "Test now" I always get an "An error has occurred. Cannot read properties of null (reading 'forEach')" error.

I wanted to try an older version of the connector, but I couldn't find any prior version to download.

Any help will be appreciated.

**Comment by eliykat** [comment]
Hi @amansilla, this is something that our Customer Success team can help you configure and troubleshoot. Please contact them here for further assistance: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

Thanks!
