### ISSUE TITLE
LDAP sync doesn't work with on-prem server

### ISSUE THREAD

**Issue by Domsdagr** [bitwarden/directory-connector#259]
Hey, I hope someone here can help me.

I have installed a bitwarden docker instance on a CentOS 8 server and wanted to implement LDAP synchronization. The sync worked using the cloud instance but as soon as I try to use my own server I get the error message:

request to https://<sub.domain.tld>/identity/connect/token failed, reason: unable to verify the first certificate

I have checked everything that comes to my mind, I have exhausted google searches up until page 5, I have added the root certificate to the trusted list using the "update-ca-trust" command. I have no idea what else I can try.

Maybe someone here is able to help me with that? This is about my final project, so kinda my whole future depends on that bitwarden instance. :D

**Comment by eliykat** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
