### ISSUE TITLE
Operational issues and rethinking integration into Bitwarden

### ISSUE THREAD

**Issue by edermi** [bitwarden/directory-connector#30]
As far as I understood, the cli is only supposed to be used once it was set up with the Desktop application. This makes no sense in my opinion:

- Bitwarden itself runs on Docker which runs on Linux (yes, there are Windows / OS X solutions but let's consider a serious productive setup)
- Linux servers usually have no GUI
- Having the sync functionality on the same server, accessible by different users, is desirable in many scenarios (like multiple admins in charge of Bitwarden)

It's a pain to set up the sync using the CLI only and to be honest, every time I'm using it I'm in fear of destroying the company's complete password data.

The GUI application makes me feel a little more comfortable, but comes also with downsides. Since it has an administrative token for Bitwarden (without 2-FA) stored somewhere, having it stored next to my browser history doesn't feel good. Even if you move it to a "considered-secure" server, a remaining issue is that the configuration is stored in a user's profile. It makes administration of users impossible for multiple Bitwarden admins.

To conclude, I really like Bitwarden but the directory connector gives me regular headaches. It's unmaintainable in a scenario with more than one administrator and a headless Bitwarden server.  

I've been thinking about solutions to this problem for quite some time. I think the most solid and user friendly option is to integrate it into the web interface or admin backend. Since the data format of the console and GUI application are the same, I'd come up with the following (probably naive) setup:

- a new container, directory-sync or something, runs alongside the other containers in the on-prem scenario. It shouldn't be large or consume a lot of resources since it only needs bwdc-cli and its requirements.
- the GUI application is moved to the web/admin interface. I don't know how much work this is, but I (again, me being naive) would believe that when there's a nodejs application that needs to go into a browser, big parts of the code can be copied over with little modifications.
- Changes in the GUI are synchronized to the bwdc-cli container. Communication and synchronization between the web frontend and the cli are probably the harder parts here and since I'm not too familiar with the Bitwarden architecture, I don't have a suggestion on how to achieve this yet.

In my opinion, the manual and outsourced directory sync is a show stopper for many organizations since it is hard to maintain even with small teams. I'd love to hear your opinions and discuss problems/solutions.

**Comment by kspearrin** [comment]
> As far as I understood, the cli is only supposed to be used once it was set up with the Desktop application.

You can certainly use the CLI without the companion desktop app on a headless system. That's why we created it.

Your suggested solution is not a bad one. It makes sense, but it is not possible for scenarios where a company wants to use AD sync with the cloud-hosted solution.

**Comment by Jared-Harrington-Gibbs** [comment]
Since the GUI is a nodejs app is there anything preventing the current iteration from just being launched in a docker container and persisting settings/other information to a volume?

This would allow for more tightly coupling it with the on-premise version, via launching as part of the bitwarden.sh script, while simultaneously still allowing it to be run as a standalone application via a docker run command.

**Comment by haneef95** [comment]
Hi,

Could this be containerised, like the Bitwarden server-side please?

This is essentially a pieces of software that usually runs on a server, not on local machines.

Thanks,

**Comment by haneef95** [comment]
It would be amazing if this can be integrated into the Business Portal, similar to SSO. It'll be seamless with the rest of the setup.

A major client with 1000s of employees chose LastPass over Bitwarden just because of this.

In the meantime, is there anyway to use the same instance for multiple sync profiles/bitwarden organisations?

Thanks,

**Comment by danielfm** [comment]
This tool is a ticking time bomb. For some reason it just removed hundreds of users from my organization and now I have to spend days inviting/accepting everyone back again.

This is really frustrating.

**Comment by haneef95** [comment]
What do you guys think about [SCIM as an alternative to Directory Connector for user management](https://community.bitwarden.com/t/scim-as-an-alternative-to-directory-connector-for-user-management/28913)

Most IdPs support provisioning via SCIM, including Azure AD.

**Comment by edermi** [comment]
As far as I can see it doesn't support Active Directory.

**Comment by haneef95** [comment]
@edermi - Yes, same. I don't think Active Directory has SCIM support. However, Azure AD Free supports upto 50k objects and has User Provisioning. So, it could be done that way.

AD -> Azure AD Connect (for OnPremises Data Sync) -> AzureAD -> Provisioned via SCIM to Service Providers (e.g: Bitwarden)

That way, AD Admins won't need to install vendor specific Directory Sync Tools for each service. They could just use the AAD provisioning tool out-of-the-box and as a SaaS.

**Comment by edermi** [comment]
This is a different discussion. There are many reasons not to use cloud products. 

This issue is about integration of the existing sync client, which supports more directory services than your proposed solution, into the server components.

**Comment by eliykat** [comment]
Hi all! In the time since this issue was opened, we've relocated feature requests and user-to-user support to the community forums. I'll close this thread, but please feel free to create a new post in the community forums to discuss alternative solutions or to request a change in our approach. This will make sure we can track and triage the feature request properly.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
