### ISSUE TITLE
Please add keycloak support

### ISSUE THREAD

**Issue by plansten** [bitwarden/directory-connector#464]
I have self hosted bitwarden and keycloak v21.1.1.
Please add keycloak support.

**Comment by daniellbw** [comment]
Hi @plansten ,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
