### ISSUE TITLE
Support full Group Search API for G Suite connector

### ISSUE THREAD

**Issue by Tomasvrba** [bitwarden/directory-connector#63]
As described in the [documentation](https://bitwarden.com/help/article/user-group-filters/#g-suite):
> The G Suite APIs do not provide a way to filter groups directly, however, you can use our custom filtering syntax that allows you to exclude or include a comma separated list of group names.

However, I believe this is no longer the case:
https://developers.google.com/admin-sdk/directory/v1/guides/search-groups

The API should support searches by `email`, `name` and `memberKey` with custom operators for equality (`=`) and `:{PREFIX}*` allowing you to filter groups more dynamically. For example, it would be fantastic to prefix all Bitwarden related groups with `BITWARDEN-...` in G suite and then include them in the directory connector filter with a single expression `name:BITWARDEN-*` so that even groups with this prefix created in the future are synced.

**Comment by kspearrin** [comment]
Yes, this does appear to be possible now.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
