### ISSUE TITLE
Include Group Syntax not working as expected...

### ISSUE THREAD

**Issue by mrventerj** [bitwarden/directory-connector#68]
Hi 

I did do the first method   "Include:Group A " but then I have to specify each users under users before they get an invite.

So the second method is (from my understanding) invite all users in the group by using the syntax 'includeGroup:xxxx-xxxx-xxx"

I clicked test - but I was expecting only my test group to appear and the one test user,  but the test that run listed all the groups I have in Azure AD.

Is this normal behavior?

Kind Regards,

**Comment by mrventerj** [comment]
@kspearrin Sorry for direct @ - do you have any insight on the question above?

**Comment by kspearrin** [comment]
@sevensixseven Could you take a look into this?

**Comment by sevensixseven** [comment]
@mrventerj I am happy to help. One thing to remember is that `Sync users` and `Sync groups` are two separate queries. The `Sync users` is specifically to return only users and `Sync groups` is specifically to return only groups. You will not be able to only set a `Group Filter` under `Sync groups` and expect to return any users. To return a set of users under a group in Azure AD, you will want to use the `includeGroup:` filter under `Sync users`. If you would also like to sync specific groups from Azure AD then you will want to specify them using the `include:` filter under `Sync groups`. Once the users are returned and the groups are returned then they will be married or associated with each other based on a user's attributes which specify the groups they are members of. Just another thing to note, the `User Path` or `Group Path` is the starting point of the query to narrow your scope before applying any filters rather than starting at the root of your directory and querying everything. I hope this helps, please let me know if you have any other questions.

**Comment by clayadams5226** [comment]
Hi @mrventerj , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.
